### ISSUE TITLE
somebody help me.......

### ISSUE THREAD

**Issue by JJJJJAE** [kyukyukyu/oop-mentoring#4]
i don't know. how to solve this error

**Comment by JJJJJAE** [comment]
![kakaotalk_20180731_181254650](https://user-images.githubusercontent.com/41948141/43451058-062ed050-94ef-11e8-83fd-40f8d3b6141c.jpg)

**Comment by JJJJJAE** [comment]
This code happened when I wrote below code.  
![kakaotalk_20180731_181254650](https://user-images.githubusercontent.com/41948141/43451364-ba917ef8-94ef-11e8-9b3c-9d7ca20dea88.jpg)

**Comment by kyukyukyu** [comment]
It looks like this issue is sort of spam to me. To be kind to you, and for my English, I decided to reply this.
This repo is not for general questions like what you wrote. I've created this repo to archive the stuffs that I used for mentoring folks in an OOP class when I was in a university. (It's already been three years since then.)
Now that class is over, I'm leaving this repo inactive. However, if someone needs help about OOP concepts, I'll be pleased to give her/him a help.

I know these are kind of TMI, but your spam just reminds me the old days, and I'm just in a mood to write down some words. Good luck on your.. camera something!
